name: Deploy cache
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - master

jobs:
  build-cache:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: master
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up uv
      uses: astral-sh/setup-uv@v4

    - name: Sync disposable dependencies
      run: |
        cd disposable
        uv sync

    - name: Run Python script
      run: |
        uv --project disposable run python generate-cache.py

    - name: Commit files to gh-pages branch
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'

        # Switch to gh-pages branch
        git checkout -b gh-pages

        # Add all generated files (if your script generates files to be committed)
        git add cache/ --force

        # Copy README_pages.md to README.md
        cp README_pages.md README.md

        # overwrite default readme.md
        git add README.md

        # Commit the changes
        git commit -m "Update cache [skip ci]" && git push origin gh-pages --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
